version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: na-ordinals_ord_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  ord:
    image: nateanderson/ord:0.16.0@sha256:3fff68f9e493f4cd326c01326972ce75cd52f8c707731cc1a4b3009d595a3a7a
    # This needs to run as root
    # user: "1000:1000"
    restart: on-failure
    # First-inscription-height may not be needed in the future
    command: "--data-dir /var/lib/ord --bitcoin-data-dir /var/lib/bitcoind --bitcoin-rpc-url ${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT} --chain ${APP_BITCOIN_NETWORK} server --http"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/ord
      - ${APP_BITCOIN_DATA_DIR}:/var/lib/bitcoind:ro